### ISSUE TITLE
nginx ingress annotations are ignored

### ISSUE THREAD

**Issue by smnbbrv** [DVPE-cloud/aws-helm-service-chart#28]
Hi guys,

trying to set SSL redirect to true but seems this settings 

https://github.com/DVPE-cloud/aws-helm-service-chart/blob/4bbe620564241aca7cd8089549f6fab999f458d6/values.yaml#L117

are not used at

https://github.com/DVPE-cloud/aws-helm-service-chart/blob/4bbe620564241aca7cd8089549f6fab999f458d6/templates/ingress.yaml#L41

**Comment by christodo** [comment]
Hi @smnbbrv, 

yes, seems to be a bug. We will have a look. 
Thanks for reporting 👍
